# deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    com.musify.service: express
  name: express
spec:
  replicas: 1
  selector:
    matchLabels:
      com.musify.service: express
  strategy: {}
  template:
    metadata:
      labels:
        com.musify.service: express
    spec:
      containers:
        image: express
        name: express
        ports:
          - containerPort: 3000
            hostPort: 3000
            protocol: TCP
        resources: {}
      restartPolicy: Always
status: {}
---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    com.musify.service: express
  name: express
spec:
  ports:
    - name: "3000"
      port: 3000
      targetPort: 3000
  selector:
    com.musify.service: express
---
# configmap
apiVersion: v1
kind: ConfigMap
metadata:
  name: express-configmap
data:
  EMAIL: musifymail@gmail.com
