apiVersion: v1
kind: PersistentVolume
metadata:
  name: minio-storage-volume
spec:
  storageClassName: minio-storage-class
  capacity:
    storage: 2Gi
  accessModes:
  - ReadWriteOnce
  persistentVolumeReclaimPolicy: Delete
  hostPath:
    path: /data
