# storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: minio-storage-class
provisioner: microk8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer

---
# statefulset
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    com.musify.service: minio
  name: minio
spec:
  serviceName: "minio"
  replicas: 1
  selector:
    matchLabels:
      com.musify.service: minio
  template:
    metadata:
      labels:
        com.musify.service: minio
    spec:
      containers:
        - image: jakepel03/musify-minio:1.0
          name: minio
          envFrom:
            - configMapRef:
                name: musify-configmap
            - secretRef:
                name: musify-secrets
          ports:
            - containerPort: 9000
          volumeMounts:
            - mountPath: /data
              name: minio-storage-volume
          readinessProbe:
            httpGet:
              path: /minio/health/live
              port: 9000
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
          livenessProbe:
            httpGet:
              path: /minio/health/ready
              port: 9000
            initialDelaySeconds: 20
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
  volumeClaimTemplates:
    - metadata:
        name: minio-storage-volume
      spec:
        storageClassName: minio-storage-class
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi

---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    com.musify.service: minio
  name: minio
spec:
  ports:
    - name: "9000"
      port: 9000
      targetPort: 9000
  selector:
    com.musify.service: minio