# storage class
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: postgres-storage-class
provisioner: microk8s.io/hostpath
volumeBindingMode: WaitForFirstConsumer

---
# stateful set
apiVersion: apps/v1
kind: StatefulSet
metadata:
  labels:
    com.musify.service: postgres
  name: postgres
spec:
  serviceName: postgres
  replicas: 1
  selector:
    matchLabels:
      com.musify.service: postgres
  template:
    metadata:
      labels:
        com.musify.service: postgres
    spec:
      containers:
        - image: jakepel03/musify-db:1.0
          name: postgres
          envFrom:
            - configMapRef:
                name: musify-configmap
            - secretRef:
                name: musify-secrets
          ports:
            - containerPort: 5432
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-data
          readinessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - -e
                - |
                  exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
                  [ -f /opt/bitnami/postgresql/tmp/.initialized ] || [ -f /bitnami/postgresql/.initialized ]
            failureThreshold: 3
            initialDelaySeconds: 5
            periodSeconds: 10
            timeoutSeconds: 5
          livenessProbe:
            exec:
              command:
                - /bin/sh
                - -c
                - exec pg_isready -U "postgres" -h 127.0.0.1 -p 5432
            failureThreshold: 3
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
      restartPolicy: Always
  volumeClaimTemplates:
    - metadata:
        name: postgres-data
      spec:
        storageClassName: postgres-storage-class
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 1Gi

---
# service
apiVersion: v1
kind: Service
metadata:
  labels:
    com.musify.service: postgres
  name: postgres
spec:
  ports:
    - name: "5432"
      port: 5432
      targetPort: 5432
  type: ClusterIP
  selector:
    com.musify.service: postgres
