FROM node:20 AS builder

WORKDIR /builder

COPY react/musify .

RUN npm install \
    && npm run build

FROM nginx:alpine

COPY --from=builder /builder/dist/ /usr/share/nginx/html
COPY nginx.conf /etc/nginx/conf.d/default.conf

CMD ["nginx", "-g", "daemon off;"]


