FROM node:20 AS builder

WORKDIR /builder

COPY express/ .

RUN npm install \
  && npx prisma generate \
  && npm run build

FROM gcr.io/distroless/nodejs20

WORKDIR /musify

COPY --from=builder /builder .

EXPOSE 3000

CMD ["dist/server.js"]
